---
title: "Trabalho Final"
author: "Paulo Brandão/Gabriel Victor"
date: '2022-06-27'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set Local
```{r setlocal}
setwd('C:/Users/paulo.brandao/Downloads/regressao-e-clustering-r')
getwd()
```

## Use Libs
```{r uselibs, message=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
```

## Análise exploratória

Importamos os dados

```{r vendasonline, message=FALSE}
  floresta_fogo <- readr::read_csv('forest_fires.csv')
```

Vemos uma amostra das informaçoes disponíveis

```{r vendasonlineview}
  head(floresta_fogo)
```

Removemos os NA's

```{r vendas_parse, message=FALSE}
  floresta_fogo = floresta_fogo %>% 
  mutate(Classes = recode(Classes, "fire" = 1, "not fire" = 0)) %>% 
  na.omit(floresta_fogo$Classes)
```

Trocamos os tipos das colunas

```{r trocartiposdascolunas}

  floresta_fogo$Temperature <- as.numeric(as.character(floresta_fogo$Temperature))
  floresta_fogo$RH <- as.numeric(as.character(floresta_fogo$RH))
  floresta_fogo$Ws <- as.numeric(as.character(floresta_fogo$Ws))
  floresta_fogo$Rain <- as.numeric(as.character(floresta_fogo$Rain))
  floresta_fogo$FFMC <- as.numeric(as.character(floresta_fogo$FFMC))
  floresta_fogo$DMC <- as.numeric(as.character(floresta_fogo$DMC))
  floresta_fogo$DC <- as.numeric(as.character(floresta_fogo$DC))
  floresta_fogo$ISI <- as.numeric(as.character(floresta_fogo$ISI))
  floresta_fogo$BUI <- as.numeric(as.character(floresta_fogo$BUI))
  floresta_fogo$FWI <- as.numeric(as.character(floresta_fogo$FWI))
  floresta_fogo$day <- as.numeric(as.character(floresta_fogo$day))
  floresta_fogo$month <- as.numeric(as.character(floresta_fogo$month))
  floresta_fogo$year <- as.numeric(as.character(floresta_fogo$year))
  
  head(floresta_fogo)
```


> Random Forest

Adicionamos a biblioteca

```{r random_forest_lib_add}
  library(randomForest)
  require(caTools)
  
  library(rpart)
  library(rpart.plot)
  require("caret")
```

Dividimos os dados:
```{r entropia}
  floresta_fogo<-floresta_fogo[!(floresta_fogo$day=="day" | floresta_fogo$day=="Sidi-Bel Abbes Region Dataset"),]
  
  ind = createDataPartition(floresta_fogo$Classes,p = 0.8, 1, list = F)
  
  train = floresta_fogo[ind,]
  test  = floresta_fogo[-ind,]
  View(test)
  View(train)
```

Treinamos o modelo e plotamos no final

```{r random_forest_generate_2}
  model1 <- randomForest(
    x = train[,-14],
    y = train$Classes,
    xtest = test[,-14],
    ytest = test$Classes,
    data = train, 
    importance = TRUE,
    ntree = 50,
    keep.forest = T,
    mtry = 10,
    nodesize = 10,
    maxnode = 14
    )
  plot(model1)
  getTree(model1,1)
  varImpPlot(model1)
```




## Clusterização

```{r loadlibcluster}
# Loading package
library(ClusterR)
library(cluster)
```

```{r cluster}
  dados <- floresta_fogo
  dados <- subset(dados, select = c(Temperature, Rain, RH))
  
  
  set.seed(240) # Setting seed
  cls <- kmeans(dados, centers = 3, nstart = 20)
```

```{r defineclusters}
  dados$cluster <- as.character(cls$cluster)
  head(cls)
```

```{r plot clusters}

ggplot() +
  geom_point(data = dados, 
             mapping = aes(x = Temperature, 
                                  y = Rain, 
                                  colour = cluster))+
  geom_point(mapping = aes_string(x = cls$centers[, "Temperature"], 
                                  y = cls$centers[, "Rain"]),
                                  color = "red", size = 4) +
  geom_text(mapping = aes_string(x = cls$centers[, "Temperature"], 
                                  y = cls$centers[, "Rain"],
                                 label = 1:3),
                                  color = "black", size = 4) +
  theme_light()
```



